export const _talentMembers = [
  {
    img: 'assets/img/members/talent-1.webp',
    name: 'Ron Z',
    title: 'Web Developer',
    address: 'Los Angeles, CA',
    rate: 5,
    reviews: 500,
    summary: "We use best practices in Agile Software Development and project management. While maintaining regular communication with our clients we also ensure every project to be completed in time. If testing is in scope of a project, we prefer TDD. ",
    hourly: 22,
    country: "United State",
    skills: ['Angular', 'React', 'Vue'],
  },
  {
    img: 'assets/img/members/talent-2.webp',
    name: 'Sergey M',
    title: 'Full-Stack Developer',
    address: 'Los Angeles, CA',
    rate: 5,
    reviews: 500,
    summary: "We use best practices in Agile Software Development and project management. While maintaining regular communication with our clients we also ensure every project to be completed in time. If testing is in scope of a project, we prefer TDD. ",
    hourly: 22,
    country: "United State",
    skills: ['Angular', 'React', 'Vue'],
  },
  {
    img: 'assets/img/members/talent-3.webp',
    name: 'David K',
    title: 'FrontEnd Developer',
    address: 'Los Angeles, CA',
    rate: 5,
    reviews: 500,
    summary: "We use best practices in Agile Software Development and project management. While maintaining regular communication with our clients we also ensure every project to be completed in time. If testing is in scope of a project, we prefer TDD. ",
    hourly: 22,
    country: "United State",
    skills: ['Angular', 'React', 'Vue'],
  },
  {
    img: 'assets/img/members/talent-4.webp',
    name: 'Mike V',
    title: 'DevOps Developer',
    address: 'Los Angeles, CA',
    rate: 5,
    reviews: 500,
    summary: "We use best practices in Agile Software Development and project management. While maintaining regular communication with our clients we also ensure every project to be completed in time. If testing is in scope of a project, we prefer TDD. ",
    hourly: 22,
    country: "United State",
    skills: ['Angular', 'React', 'Vue'],
  },
  {
    img: 'assets/img/members/talent-5.webp',
    name: 'Jennifer M',
    title: 'UI/UX Designer',
    address: 'Los Angeles, CA',
    rate: 5,
    reviews: 500,
    summary: "We use best practices in Agile Software Development and project management. While maintaining regular communication with our clients we also ensure every project to be completed in time. If testing is in scope of a project, we prefer TDD. ",
    hourly: 22,
    country: "United State",
    skills: ['Angular', 'React', 'Vue'],
  },
  {
    img: 'assets/img/members/talent-6.webp',
    name: 'Yahor D',
    title: 'Backend Developer',
    address: 'Los Angeles, CA',
    rate: 5,
    reviews: 74,
    summary: "We use best practices in Agile Software Development and project management. While maintaining regular communication with our clients we also ensure every project to be completed in time. If testing is in scope of a project, we prefer TDD. ",
    hourly: 22,
    country: "United State",
    skills: ['Angular', 'React', 'Vue'],
  },
  {
    img: 'assets/img/members/talent-7.webp',
    name: 'Amy B',
    title: 'Accounting Consultant',
    address: 'Los Angeles, CA',
    rate: 5,
    reviews: 63,
    summary: "We use best practices in Agile Software Development and project management. While maintaining regular communication with our clients we also ensure every project to be completed in time. If testing is in scope of a project, we prefer TDD. ",
    hourly: 22,
    country: "United State",
    skills: ['Angular', 'React', 'Vue'],
  },
  {
    img: 'assets/img/members/talent-8.webp',
    name: 'Joshua B',
    title: 'Data Engineer',
    address: 'Los Angeles, CA',
    rate: 5,
    reviews: 206,
    summary: "We use best practices in Agile Software Development and project management. While maintaining regular communication with our clients we also ensure every project to be completed in time. If testing is in scope of a project, we prefer TDD. ",
    hourly: 22,
    country: "United State",
    skills: ['Angular', 'React', 'Vue'],
  },
]
export const _topSkills = [
  "Android Developer",
  "Bookkeeper",
  "Content Writer",
  "Copywriter",
  "Customer Service Representative",
  "Database Administrator",
  "Data Scientist",
  "Facebook Developer",
  "Front - End Developer",
  "Game Developer",
  "Graphic Designer",
  "Information Security Analyst",
  "iOS Developer",
  "Java Developer",
  "JavaScript Developer",
  "Logo Designer",
  "Mobile App Developer",
  "PHP Developer",
  "Python Developer",
  "Resume Writer",
  "Sales Consultant",
  "SEO Expert",
  "Social Media Manager",
  "Software Developer",
  "Software Engineer",
  "Technical Writer",
  "UI Designer",
  "UX Designer",
  "Virtual Assistant",
  "Web Designer",
  "Wordpress Developer"
];
export const _trendingSkills = [
  "Apple UIKit",
  "Apple Xcode",
  "Articulate storyline",
  "Atlassian Confluence",
  "Blockchain",
  "Customer retention",
  "eLearning",
  "Enterprise architecture",
  "GitLab",
  "Go development",
  "Google App Engine API",
  "Google Cloud Platform",
  "Node.js",
  "Product photography",
  "Rapid prototyping",
  "Risk management",
  "Scala development",
  "SCORM",
  "Tensorflow",
  "Volusion",
  "Dropbox API",
  "iPhone UI design",
  "Genetic algorithms",
  "Vue.js",
  "Social customer service",
  "HR consulting",
  "Oculus Rift",
  "Microsoft Power BI",
  "Proposal writing",
  "Vuforia",
  "Instructional design",
  "React.js"
]
